---
version: 2
plan:
  project-key: SIMPLE
  name: HelloWorldPlan
  key: HWP
  description: A simple plan that prints Hello, World!

stages:
  - HelloWorldStage:
      description: A stage that contains a job to print Hello, World!
      manual: false
      final: false
      jobs:
        - name: HelloWorldJob
          key: HWJ
          description: A job that executes a script to print Hello, World!
          clean-working-dir: true
          tasks:
            - script:
                description: Print Hello, World!
                interpreter: BINSH_OR_CMDEXE
                scriptBody: |
                  echo "Hello, World!"

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: false

notifications: []

labels: []

dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true

plan-permissions:
  - roles:
      - logged-in
      - anonymous
    permissions:
      - view
...
